eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
spring:
    application:
        name: cloud-hello
    zipkin: 
        baseUrl: http://localhost:9411/
    sleuth:
        sampler:
            percentage: 100.0
        
failAfter:
    enabled=false
    count=100
    
serverId: 'Cloud-Hello'

    
logging:
    level: 
        root: 'INFO'
        org.springframework: 'INFO'